scormpk/Controllers/Files/FilesController.cs
using Microsoft.Office.Core;
using Microsoft.Office.Interop.PowerPoint;
using scormpk.Controllers.Settings;
using scormpk.Models;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Spire.Presentation;
using System.Drawing.Imaging;

namespace scormpk.Controllers.Files
{
    public class FilesController : Controller
    {
        [HttpPost]
        public ActionResult UploadFiles(HttpPostedFileBase file)
        {
            try
            {
                using (scormpkcon db = new scormpkcon())
                {
                    var filesize = 2097152;
                    var supportedTypes = new[] { "ppt", "pptx" };
                    var fileExt = System.IO.Path.GetExtension(file.FileName).Substring(1);
                    if (!supportedTypes.Contains(fileExt))
                    {
                        TempData["Errormsg"] = "File Extension Is InValid - Only Upload PPT / PPTX File";
                        return RedirectToAction("Index", "Scorm");
                    }
                    else if (file.ContentLength > filesize)
                    {
                        TempData["Errormsg"] = "File size Should Be UpTo 2 MB";
                        return RedirectToAction("Index", "Scorm");
                    }
                    else
                    {
                        //Uploading File
                        string filename = Guid.NewGuid() + Path.GetExtension(file.FileName);
                        file.SaveAs(Path.Combine(Server.MapPath("~/App_Data/UploadedFiles/"), filename));
                        var path = Server.MapPath(@"~/App_Data/UploadedFiles/");
                        //var path = HttpContext.Current.Server.MapPath(@"~/App_Data/UploadedFiles/");
                        //Conversion

                        Spire.Presentation.Presentation presentation = new Spire.Presentation.Presentation();

                        presentation.LoadFromFile(path + filename);

                        //traverse the slides of PPT files
                        for (int i = 0; i < presentation.Slides.Count; i++)
                        {
                            //save the slide to Image
                            Image image = presentation.Slides[i].SaveAsImage();

                            String fileName = String.Format("result-img-{0}.png", i);
                            image.Save(filename, ImageFormat.Jpeg);
                            //view the image
                            System.Diagnostics.Process.Start(fileName);
                        }

                        //Saving Database
                        tblFile f = new tblFile();
                        f.FileID = ProgramSettings.assignId("tblFiles", "FileID", "");
                        f.FileName = file.FileName;
                        f.FileGUID = filename;
                        db.tblFiles.Add(f);
                        db.SaveChanges();
                        TempData["Errormsg"] = "File has been successfully uploaded";
                        return RedirectToAction("Index", "Scorm");
                        //return Json(new { status = "success", data = "File Uploaded Successfully" }, JsonRequestBehavior.AllowGet);
                    }
                }
            }
            catch (Exception x)
            {
                TempData["Errormsg"] = x.Message;
                return RedirectToAction("Index", "Scorm");
            }
        }
        //[HttpPost]
        //public ActionResult UploadFiles(HttpPostedFileBase file)
        //{
        //    string guid = Guid.NewGuid().ToString();


        //    string msg = "Something went wrong, Your file was not uploaded.";
        //    string FinalPath = "";
        //    if (file != null && file.ContentLength < 2097152)
        //    {
        //        var fileName = Path.GetFileName(file.FileName);             // extract only the filename
        //        var ext = Path.GetExtension(fileName.ToLower());  
        //        if (ext == ".ppt" || ext == ".pptx")
        //        {
        //            Microsoft.Office.Interop.PowerPoint.Presentation pptPresentation = pptApplication.Presentations.Open2007(fileName);
        //            foreach (Microsoft.Office.Interop.PowerPoint.Slide pptSlide in pptPresentation.Slides)
        //            {
        //                pptSlide.Export("SlidesTest", "PNG", 1024, 768);
        //            }
        //        }
        //    }
        //    return View();
        //}
    }
}

scormpk/Controllers/Website/ScormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace scormpk.Controllers.Website
{
    public class ScormController : Controller
    {
        // GET: WebsiteMain
        public ActionResult Index()
        {
            return View();
        }
    }
}

scormpk/Views/Scorm/Index.cshtml
@{
    ViewBag.Title = "Convert PowerPoint to SCORM, for free";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<!--================ Banner Section start =================-->
<section class="hero-banner text-center">
    <div class="container">
        @{
            if (TempData["Errormsg"] != null)
            {
                <p class="text-uppercase text-warning">@TempData["Errormsg"].ToString()</p>
                <h1 data-animate-in="up">Convert PowerPoint to SCORM, for free</h1>
                <p class="hero-subtitle">Do you want to create your SCORM from your PowerPoint? Choose a file below and convert it now — 100% online — no software required</p>
            }
            else
            {
                <p class="text-uppercase">SCROM CONVERTER</p>
                <h1 data-animate-in="up">Convert PowerPoint to SCORM, for free</h1>
                <p class="hero-subtitle">Do you want to create your SCORM from your PowerPoint? Choose a file below and convert it now — 100% online — no software required</p>
            }
        }
        @using (Html.BeginForm("UploadFiles", "Files", FormMethod.Post, new { @enctype = "multipart/form-data" }))
        {
            @*<div class="form-group files">
                <label>Upload Your File </label>
                <input type="file" class="form-control" name="file">
            </div>
            <input type="submit" class="button" value="Upload" />*@

            <div class="drag-area">
                <svg xmlns="http://www.w3.org/2000/svg" width="50" height="43" viewBox="0 0 50 43">
                    <path d="M48.4 26.5c-.9 0-1.7.7-1.7 1.7v11.6h-43.3v-11.6c0-.9-.7-1.7-1.7-1.7s-1.7.7-1.7 1.7v13.2c0 .9.7 1.7 1.7 1.7h46.7c.9 0 1.7-.7 1.7-1.7v-13.2c0-1-.7-1.7-1.7-1.7zm-24.5 6.1c.3.3.8.5 1.2.5.4 0 .9-.2 1.2-.5l10-11.6c.7-.7.7-1.7 0-2.4s-1.7-.7-2.4 0l-7.1 8.3v-25.3c0-.9-.7-1.7-1.7-1.7s-1.7.7-1.7 1.7v25.3l-7.1-8.3c-.7-.7-1.7-.7-2.4 0s-.7 1.7 0 2.4l10 11.6z">
                    </path>
                </svg>
                <input type="file" name="file" id="file" required="required">
                <label for="file"><strong><span>Choose a file</span></strong><span> <span>or drag it here</span></span>.</label>
            </div>
            <input type="submit" class="button" value="Upload" />

        }
    </div>
</section>
<!--================ Banner Section end =================-->
<!--================ Online Courses section start =================-->
<section class="section-margin">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-5 mb-5 mb-lg-0">
                <h2 data-animate-in="up" class="mb-4">Create online courses for free </h2>
                <p data-animate-in="fadeIn">Stop spending money with authoring tools. With ScormHero, all you need is a PowerPoint with the content of your course, and let our hero do the trick. Then, you just have to download it, and import to your favorite LMS or host in your website.</p>
                <a class="button" href="#top">Get Started</a>
            </div>
            <div class="col-lg-7">
                <div class="text-center">
                    <img data-animate-in="right" class="img-fluid product" height="500" width="500" src="../assets/img/home/server.png" alt="">
                </div>
            </div>
        </div>
    </div>
</section>
<!--================  Online Courses section end =================-->
<div class="container">
    <hr>
</div>
<!--================ Add Quiz section start =================-->
<section class="section-margin">
    <div class="container">
        <div class="row align-items-center">

            <div class="col-lg-7">
                <div class="text-center">
                    <img data-animate-in="left" class="img-fluid product" height="500" width="500" src="../assets/img/home/addquizz.jpg" alt="">
                </div>
            </div>
            <div class="col-lg-5 mb-5 mb-lg-0">
                <h2 data-animate-in="up" class="mb-4">Add quiz and convert with audio</h2>
                <p data-animate-in="fadeIn">Do you want customize your course, like adding quiz, your company logo and more? Check out these and other features available in our plan ScormHero PRO. And don't panic: it costs 10 times less than other authoring tools (monthly).</p>
                <a class="button" href="#top">Get Started</a>
            </div>
        </div>
    </div>
</section>
<!--================  Add Quiz section end =================-->
<div class="container">
    <hr>
</div>
<!--================ Deliver section start =================-->
<section class="section-margin">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-5 mb-5 mb-lg-0">
                <h2 data-animate-in="up" class="mb-4">Deliver and track your courses</h2>
                <p data-animate-in="fadeIn">Besides creating your course, don't want struggle to find a place to host and send to your students, that's your place. Check out other plans that offers you a simple and cost-effective way to manage elearning.</p>
                <a class="button" href="#top">Get Started</a>
            </div>
            <div class="col-lg-7">
                <div class="text-center">
                    <img data-animate-in="right" class="img-fluid product" height="500" width="500" src="../assets/img/home/Deliver.jpg" alt="">
                </div>
            </div>
        </div>
    </div>
</section>
<!--================  Deliver section end =================-->
<div class="container" id="pricing">
    <hr>
</div>
<!--================ Price Table section start =================-->
<section class="section-padding">
    <div class="container">
        <div class="pb-85px text-center">
            <h2>Plans and Pricing</h2>
            <div class="section-style"></div>
        </div>

        <div class="row">
            <div class="col-sm-6 col-lg-4 mb-4 mb-lg-0" data-animate-in="left">
                <div class="card text-center card-pricing">
                    <div class="card-pricing__header">
                        <h4>Free</h4>
                        <h1 class="card-pricing__price"><span>$</span>0</h1>
                        <p>per month</p>
                    </div>
                    <ul class="card-pricing__list">
                        <li>50mb max upload size</li>
                        <li>Limited 5 conversions/day</li>
                    </ul>
                    <div class="card-pricing__footer">
                        <a href="#top"><button class="button">Get Started</button></a>
                    </div>
                </div>
            </div>

            <div class="col-sm-6 col-lg-4 mb-4 mb-lg-0" data-animate-in="up">
                <div class="card text-center card-pricing">
                    <div class="card-pricing__header">
                        <h4>Pro</h4>
                        <h1 class="card-pricing__price"><span>$</span>19</h1>
                        <p>per month</p>
                    </div>
                    <ul class="card-pricing__list">
                        <li>Unlimited upload size</li>
                        <li>Unlimited conversions/day</li>
                        <li>Create quiz/test</li>
                        <li>24 x 7 email support</li>
                    </ul>
                    <div class="card-pricing__footer">
                        <button class="button" data-toggle="modal" data-target="#staticBackdropSignIn">Start Trail</button>
                    </div>
                </div>
            </div>

            <div class="col-sm-6 col-lg-4 mb-4 mb-lg-0" data-animate-in="right">
                <div class="card text-center card-pricing">
                    <div class="card-pricing__header">
                        <h4>Enterprise</h4>
                        <p></p>
                        <h1 class="card-pricing__price">custom</h1>
                        <p></p>
                    </div>
                    <ul class="card-pricing__list">
                        <li>Everything in Pro and</li>
                        <li>Course hosting</li>
                        <li>Student enrollment</li>
                    </ul>
                    <div class="card-pricing__footer">
                        <a href="#contact"><button class="button">Contact us</button></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--================ Price Table section end =================-->
<div class="container" id="contact">
    <hr>
</div>
<!--================ Contact section start =================-->
<section class="section-margin">
    <div class="container">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="contact-title">Can we help you?</h2>
                <p>Do you have any question? Just fill out the form field below.</p>
            </div>
            <div class="col-lg-3"></div>
            <div class="col-lg-6 mb-4 mb-lg-0">
                <form class="form-contact contact_form">
                    <div class="row">
                        <div class="col-12">
                            <div class="form-group">
                                <input class="form-control" id="txtname" type="text" placeholder="Enter Full Name">
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group">
                                <input class="form-control" id="txtemail" type="text" placeholder="Enter E-mail">
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group">
                                <textarea class="form-control w-100" id="txtmessage" cols="30" rows="9" placeholder="Type your message"></textarea>
                            </div>
                        </div>
                    </div>
                    <div class="form-group mt-lg-3">
                        <button id="btnSend" class="button">Send Message</button>
                    </div>
                </form>
            </div>
            <div class="col-lg-3"></div>
        </div>
    </div>
</section>
<!--================ Contact section end =================-->
<!--Script Section-->
<script src="../jQueryScripts/FileUploading/Files.js"></script>
<script src="../Scripts/jquery.filedrop.js"></script>
<script src="../Scripts/sweetalert.min.js"></script>
<script src="../Scripts/jquery-3.5.1.min.js"></script>
<script src="../jQueryScripts/SendEmail/SendEmail.js"></script>